load_balancer:
    image: tutum/haproxy
    links:
        - web
    ports:
        - "80:80"
    environment:
        - FORCE_SSL=0
        - SSL_CERT=0
        - VIRTUAL_HOST="laravel.local"

web:
    image: million12/nginx-php
    volumes:
        - ./../:/data
    environment:
        - NGINX_GENERATE_DEFAULT_VHOST=True
        - STATUS_PAGE_ALLOWED_IP=95.25.145.253
        - VIRTUAL_HOST="laravel.local"
