load_balancer:
    image: million12/haproxy
    links:
        - nginx
    ports:
        - "80:80"

nginx:
    image: million12/nginx-php
    volumes:
        - ./../:/data
    environment:
        - NGINX_GENERATE_DEFAULT_VHOST=true
        - STATUS_PAGE_ALLOWED_IP=95.25.145.253
