load_balancer:
    image: tutum/haproxy
    links:
        - web
    ports:
        - "80:80"

web:
    image: million12/nginx-php
    volumes:
        - ./../:/data
    environment:
        - NGINX_GENERATE_DEFAULT_VHOST=0
        - STATUS_PAGE_ALLOWED_IP=95.25.145.253
