load_balancer:
    image: dockercloud/haproxy
    links:
        - web
    ports:
        - "80:80"
    roles:
      - global

web:
    image: million12/nginx-php
    target_num_containers: 3
    volumes:
        - ./../:/data
    environment:
        - NGINX_GENERATE_DEFAULT_VHOST=0
        - STATUS_PAGE_ALLOWED_IP=95.25.145.253
