load_balancer:
    image: tutum/haproxy
    links:
        - web
    ports:
        - "80:80"

web:
    image: andrewmclagan/nginx-hhvm
    volumes:
        - ./:/var/www
    environment:
        - APP_ENV=production
        - VIRTUAL_HOST="benchmark.grinev.ru"
